# vim:set ft=sh
# MODULES
# Modules to load before mounting the root filesystem.
MODULES=()

# BINARIES
# Additional binaries to include in the initramfs.
BINARIES=()

# FILES
# Files to include in the initramfs.
FILES=()

# HOOKS
# Hooks to run during initramfs generation.
HOOKS=(base udev microcode modconf kms keyboard keymap consolefont block filesystems fsck)

# COMPRESSION
# Compression algorithm for the initramfs image.
COMPRESSION="xz"

# COMPRESSION_OPTIONS
# Extra options to pass to the compression tool.
COMPRESSION_OPTIONS=(-9)
